permissions:
  contents: read  
  
on:
  push:
    branches: [ "main" ,"test", "stagin"]
  workflow_dispatch:

jobs:
  init:
    name: CI Workflow
    uses: codeparceorg/ci-workflows/.github/workflows/init-gcp.yml@functions
    secrets: inherit
      